### ISSUE TITLE
Add "contact" information to definition

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/extensions-catalog#10]
#### Reason/Context
Knowing who to contact when using an extension might be difficult with no other information than the name of the author.

#### Description
It would be great to add a "contact" field with more information on who to contact for questions, bugs, or feature requests. The "contact" object can have the same information as the AsyncAPI one.

#### Example

```yaml
id: twitter
type: generic # Means it's an "x-" type of extension. In this case, x-twitter.
title: Twitter information
description: This extension allows you to place the Twitter account of the team/company in charge of the API.
version: '0.1.0'
author: Mike Ralphson
contact:
  email: info@theauthor.com
  url: theauthor.com/asyncapi-twitter-extension
  name: Support team
```
