### ISSUE TITLE
Add extension that handles adding more markdown content to API

### ISSUE THREAD

**Issue by derberg** [asyncapi/extensions-catalog#11]
#### Reason/Context
Last 2 weeks I conducted research over few SaaS solutions (ReDoc, Bump, Postman, APIMatic, Readmeio) on how they support AsyncAPI and OpenAPI. I was interested in finding out how they support a use case when you want to enrich your specification with some more markdown content. At the moment there is no widely adopted OAS extension for it. Some solutions just do not support it, and some just add additional functionality on top that locks you in with the vendor and make it hard to migrate. 

There was one super nice thing I saw in https://bump.sh/ -> https://help.bump.sh/asyncapi-support#adding-topics-to-your-documentation

```
x-topics:
  - title: Getting started
    content: Before using the API you need to get an API key by sending us an email.
  - title: Authentication
    content: Send the `X-API-KEY` header with all your requests.
    example: |
      ```
      $ curl \
        -X POST https://api.example.com/endpoint/ \
        -H "X-API-KEY: XXXXXX" \
      ```
```

You can basically add as many documentation topics as you want, with an additional markdown doc that of course you later can consume as you want in your UI.

I think it is super important to adopt such an extension into the extensions catalog, so vendors later support one way of doing things and make spec adoption easier.
This and other extensions could be a part of something like `x-docs` extension, and tags object could be part of it maybe?

I'm super interested in what others think.
