### ISSUE TITLE
Allow using the custom extension registries

### ISSUE THREAD

**Issue by magicmatatjahu** [asyncapi/extensions-catalog#50]
Reading the previous issues I think that we missed needed feature as custom extension registries. As I know by default AsyncAPI document should use the default extension registry which will be hosted and maintenance by the AsyncAPI Initiative. What in the case, when someone will want to use the custom registry?

My idea is adding to the spec the custom extension named as `x-extension-registries` (in the root of spec) or add to the spec (also in the root) the `extensionRegistries` keyword, where user can define the custom registries like (I will use in the examples the spec keyword):

```yaml
asyncapi: ...

extensionRegistries:
  {local_name_of_registry}:
    url: {URL for registry}
    # optional array which includes extension from registry that can be used in the doc.
    # Item will be string as name of extension
    # empty array means that everything can be used
    uses: []
```

At the moment I see only the need to define the above fields. We can extend it if we determine that there is a need.

How it will be used in the spec? Imagine that we have defined in the default registry the `x-twitter` extension so user can use it in the way:

```yaml
asyncapi: ...
info: 
  x-twitter: ...
```

and it will be valid. However, user wants to use the extension with this same name but from another, not default, extension registry, so then he/she can define it as:

```yaml
asyncapi: ...
info: 
  x-twitter:
    registry: twitterRegistry # local name of registry
    value: ... 
  
extensionRegistries:
  twitterRegistry:
    url: https://custom-registry.com
```

However, if custom registry has defined extension that isn't defined in the default registry, then user can omit the `registry` field and use extension as plain value.

I know that it can create some boilerplate, but at the moment I don't see any better alternative. Feel free to comment! :)
