### ISSUE TITLE
Add "tags" to the definition

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/extensions-catalog#9]
#### Reason/Context
Filtering extensions by the same "category" or similar functionality might be hard or impossible right now.

#### Description
It would be great to have a `tags` field on the extension's definition. 

#### Example

```yaml
id: twitter
type: generic
title: Twitter information
description: This extension allows you to place the Twitter account of the team/company in charge of the API.
version: '0.1.0'
author: Mike Ralphson
tags:
  - social
  - twitter
contributors:
  - Fran Mendez <fmvilas@gmail.com> (fmvilas.com)
definitions:
```
